services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abz-agency-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - webserver-network
      - db-network
    depends_on:
      - db

  nginx:
    image: nginx:1.25.4-alpine
    container_name: abz-agency-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - webserver-network
    depends_on:
      - app

  db:
    image: mysql:8.0.36
    container_name: abz-agency-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
  webserver-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
